retab

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,66 +12,66 @@ COM_XIST=1
 
 # Check if program has been installed
 if [ -f $PGM_PATH$PGM_NAME ]; then
-	PGM_XIST=1
+  PGM_XIST=1
 fi
 
 # Check if complier has been installed
 command -v $COM_NAME > /dev/null
 if [ $? != 0 ]; then
-	COM_XIST=0
+  COM_XIST=0
 fi
 
 # If program has been installed, ask if user wants to uninstall
 if [ $PGM_XIST -eq 1 ]; then
-	echo "$PGM_NAME already installed on this machine!"
-	echo -n "Do you want to uninstall it (y/n): "
-	read INPUT
-	if [ "$INPUT" == "y" ]; then
-		echo "rm $PGM_PATH$PGM_NAME..."
-		rm $PGM_PATH$PGM_NAME
-		
-		# If there is an error
-		if [ $? != 0 ]; then
-			echo "error while removing $PGM_NAME from $PGM_PATH" 
-		else
-			echo "$PGM_NAME successfully uninstalled :-)"
-		fi
-	fi
+  echo "$PGM_NAME already installed on this machine!"
+  echo -n "Do you want to uninstall it (y/n): "
+  read INPUT
+  if [ "$INPUT" == "y" ]; then
+    echo "rm $PGM_PATH$PGM_NAME..."
+    rm $PGM_PATH$PGM_NAME
+    
+    # If there is an error
+    if [ $? != 0 ]; then
+      echo "error while removing $PGM_NAME from $PGM_PATH" 
+    else
+      echo "$PGM_NAME successfully uninstalled :-)"
+    fi
+  fi
 
-	exit 0
+  exit 0
 fi
 
 # Exit if a C compiler does not exist on the system
 if [ $COM_XIST -eq 0 ]; then
-	echo "$COM_NAME does not exist, aborting."
-	exit 1
+  echo "$COM_NAME does not exist, aborting."
+  exit 1
 fi
 
 # Installtion
 if [ $PGM_XIST -eq 0 ] && [ $COM_XIST -eq 1 ]; then
   oldpwd=$(pwd)
   cd $SRC_PATH
-	make
+  make
 
-	# If There is an error
-	if [ $? != 0 ]; then
-		echo "-------------------------------------"
-		echo "Whoops, complie error(s), aborting."
-		echo "please email me with error message(s)"
-		echo "<chiayo.lin@gmail.com>"
-		cd ..
-		exit 1
-	else
-		echo "mv $PGM_NAME $PGM_PATH..."
-		mv $PGM_NAME $PGM_PATH
-		if [ $? != 0 ]; then
-			echo "error while moving $PGM_NAME to $PGM_PATH"
-			cd ..
-			exit 1
-		else
-			echo "$PGM_NAME successfully installed :-)"
-		fi
-	fi
+  # If There is an error
+  if [ $? != 0 ]; then
+    echo "-------------------------------------"
+    echo "Whoops, complie error(s), aborting."
+    echo "please email me with error message(s)"
+    echo "<chiayo.lin@gmail.com>"
+    cd ..
+    exit 1
+  else
+    echo "mv $PGM_NAME $PGM_PATH..."
+    mv $PGM_NAME $PGM_PATH
+    if [ $? != 0 ]; then
+      echo "error while moving $PGM_NAME to $PGM_PATH"
+      cd ..
+      exit 1
+    else
+      echo "$PGM_NAME successfully installed :-)"
+    fi
+  fi
 
 fi
 
